using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Theranos.Automation.ME.API.Model.Common
{
    public enum ErrorCodes
    {
        SUCCESS = 0,
        InvalidParameters = 20,
        InternalError = 21,
        InvalidSessionRequest = 22,
        UserDoesNotExist = 100,
        AnswersAreNotValid = 101,
        NotAllQuestionsExist = 102,
        DuplicateQuestions = 104,
        UserHasNotResetPassword = 105,
        UserIsLockedOut = 106,
        MalformedAccessToken = 107,
        EmptyAccessToken = 108,
        AccessTokenExpired = 109,
        AccessIsDenied = 110,
        UserNameEmpty = 111,
        UserNameMalformed = 112,
        DuplicateEmail = 113,
        DuplicateProviderUserKey = 114,
        DuplicateUserName = 115,
        InvalidEmail = 116,
        InvalidPassword = 117,
        InvalidProviderUserKey = 118,
        InvalidUserName = 120,
        ProviderError = 121,
        UserRejected = 122,
        InvalidAccessToken = 123,
        XMLGenerationError = 124,
        AccountNotActivated = 125,
        UserRequestDoesNotExist = 126,
        PINNumberExpired = 127,
        PINNumberDoesNotMatch = 128,
        UserAlreadyActivated = 129,
        TemporaryPasswordInvalid = 130,
        UserBlackListed = 131,
        InvalidNameForPatient = 132,
        InsufficientSearchCriteria = 200,
        DeleteNotAllowed = 201,
        LabOrderSaveFailed = 202,
        NoDataFound = 203,
        UnableToSaveData = 204,
        UserNotAssociatedWithPatient = 205,
        UnableToDeleteData = 206,
        UnableToSaveAddress = 207,
        AddressTypeInvalid = 208,
        UnableToUpdateEarlyCheckIn = 209,
        InvalidVisitId = 210,
        PastDateRequested = 211,
        FutureDateRequested = 212,
        AppointmentAlreadyTaken = 213,
        ServiceNotDefined = 214,
        AppointmentUnavailable = 215,
        AppointmentNotFound = 216,
        AppointmentDateInvalid = 217,
        PatientMustEnterAPIN = 218,
        PatientAssociatedWithUser = 219,
        PatientUserPINDoesNotMatch = 220,
        InsufficientDataToCreatePatient = 221,
        UserMustObtainPIN = 222,
        UserAssociatedWithAPatient = 223,
        InvalidPatientId = 224,
        InvalidCredentials = 225,
        MultiplePatientRecordsFound = 226,
        EmailAddressDoesNotMatch = 227,
        UnableToSubmitForTranscription = 228,
        UserAlreadyHasAnAppointment = 229,
        InvalidLabOrderToDelete = 230,
        InvalidLocationForAppointment = 231,
        NoShoppingCartFound = 232,
        TooManyTestsInLabOrder = 233,
        TwoStepAuthRequired = 301,
        ClientTrustExpired = 302,
        ClientInfoMismatch = 303,
        MissingPhoneNo = 304,
        MissingEmail = 305,
        InvalidZipcode = 306,
        UnableToEmail = 307,
        UnableToSms = 308,
        Unknown = 65535

    };
}
